force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Dummy Product</label>
    <nameField>
        <label>Dummy Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dummy Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Availability_Status__c.field-meta.xml
<CustomField>
    <fullName>Availability_Status__c</fullName>
    <label>Availability Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>Low Stock</fullName>
            </value>
            <value>
                <fullName>In Stock</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Amazon</fullName>
            </value>
            <value>
                <fullName>Annibale Colombo</fullName>
            </value>
            <value>
                <fullName>Apple</fullName>
            </value>
            <value>
                <fullName>Asus</fullName>
            </value>
            <value>
                <fullName>Attitude</fullName>
            </value>
            <value>
                <fullName>Bath Trends</fullName>
            </value>
            <value>
                <fullName>Beats</fullName>
            </value>
            <value>
                <fullName>Calvin Klein</fullName>
            </value>
            <value>
                <fullName>Casual Comfort</fullName>
            </value>
            <value>
                <fullName>Chanel</fullName>
            </value>
            <value>
                <fullName>Chic Cosmetics</fullName>
            </value>
            <value>
                <fullName>Chrysler</fullName>
            </value>
            <value>
                <fullName>Classic Wear</fullName>
            </value>
            <value>
                <fullName>Comfort Trends</fullName>
            </value>
            <value>
                <fullName>Dell</fullName>
            </value>
            <value>
                <fullName>Dior</fullName>
            </value>
            <value>
                <fullName>Dodge</fullName>
            </value>
            <value>
                <fullName>Dolce &amp; Gabbana</fullName>
            </value>
            <value>
                <fullName>Elegance Collection</fullName>
            </value>
            <value>
                <fullName>Essence</fullName>
            </value>
            <value>
                <fullName>Fashion Co.</fullName>
            </value>
            <value>
                <fullName>Fashion Diva</fullName>
            </value>
            <value>
                <fullName>Fashion Express</fullName>
            </value>
            <value>
                <fullName>Fashion Fun</fullName>
            </value>
            <value>
                <fullName>Fashion Gold</fullName>
            </value>
            <value>
                <fullName>Fashionista</fullName>
            </value>
            <value>
                <fullName>Fashion Shades</fullName>
            </value>
            <value>
                <fullName>Fashion Timepieces</fullName>
            </value>
            <value>
                <fullName>Fashion Trends</fullName>
            </value>
            <value>
                <fullName>Furniture Co.</fullName>
            </value>
            <value>
                <fullName>None</fullName>
                <default>true</default>
                <label>None</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>none</fullName>
                <default>true</default>
                <label>none</label>
            </value>
            <value>
                <fullName>beauty</fullName>
            </value>
            <value>
                <fullName>fragrances</fullName>
            </value>
            <value>
                <fullName>furniture</fullName>
            </value>
            <value>
                <fullName>groceries</fullName>
            </value>
            <value>
                <fullName>home-decoration</fullName>
            </value>
            <value>
                <fullName>kitchen-accessories</fullName>
            </value>
            <value>
                <fullName>laptops</fullName>
            </value>
            <value>
                <fullName>mens-shirts</fullName>
            </value>
            <value>
                <fullName>mens-shoes</fullName>
            </value>
            <value>
                <fullName>mens-watches</fullName>
            </value>
            <value>
                <fullName>mobile-accessories</fullName>
            </value>
            <value>
                <fullName>motorcycle</fullName>
            </value>
            <value>
                <fullName>skin-care</fullName>
            </value>
            <value>
                <fullName>smartphones</fullName>
            </value>
            <value>
                <fullName>sports-accessories</fullName>
            </value>
            <value>
                <fullName>sunglasses</fullName>
            </value>
            <value>
                <fullName>tablets</fullName>
            </value>
            <value>
                <fullName>tops</fullName>
            </value>
            <value>
                <fullName>vehicle</fullName>
            </value>
            <value>
                <fullName>womens-bags</fullName>
            </value>
            <value>
                <fullName>womens-dresses</fullName>
            </value>
            <value>
                <fullName>womens-jewellery</fullName>
            </value>
            <value>
                <fullName>womens-shoes</fullName>
            </value>
            <value>
                <fullName>womens-watches</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Dimensions_depth__c.field-meta.xml
<CustomField>
    <fullName>Dimensions_depth__c</fullName>
    <label>Depth</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Dimensions_height__c.field-meta.xml
<CustomField>
    <fullName>Dimensions_height__c</fullName>
    <label>Height</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Dimensions_width__c.field-meta.xml
<CustomField>
    <fullName>Dimensions_width__c</fullName>
    <label>Width</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Discount_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Discount_Percentage__c</fullName>
    <label>Discount Percentage</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Dummy_ID__c.field-meta.xml
<CustomField>
    <fullName>Dummy_ID__c</fullName>
    <label>Dummy ID</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Image_1__c.field-meta.xml
<CustomField>
    <fullName>Image_1__c</fullName>
    <label>Image 1</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Image_2__c.field-meta.xml
<CustomField>
    <fullName>Image_2__c</fullName>
    <label>Image 2</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Image_3__c.field-meta.xml
<CustomField>
    <fullName>Image_3__c</fullName>
    <label>Image 3</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Image_4__c.field-meta.xml
<CustomField>
    <fullName>Image_4__c</fullName>
    <label>Image 4</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Image_5__c.field-meta.xml
<CustomField>
    <fullName>Image_5__c</fullName>
    <label>Image 5</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Image_6__c.field-meta.xml
<CustomField>
    <fullName>Image_6__c</fullName>
    <label>Image 6</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Meta_Barcode__c.field-meta.xml
<CustomField>
    <fullName>Meta_Barcode__c</fullName>
    <label>Barcode</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Meta_Created_at__c.field-meta.xml
<CustomField>
    <fullName>Meta_Created_at__c</fullName>
    <label>Created at</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Meta_Qr_Code__c.field-meta.xml
<CustomField>
    <fullName>Meta_Qr_Code__c</fullName>
    <label>QR Code</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Meta_Updated_at__c.field-meta.xml
<CustomField>
    <fullName>Meta_Updated_at__c</fullName>
    <label>Updated at</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Minimum_Order_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Order_Quantity__c</fullName>
    <label>Minimum Order Quantity</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Return_Policy__c.field-meta.xml
<CustomField>
    <fullName>Return_Policy__c</fullName>
    <label>Return Policy</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>30 days return policy</fullName>
            </value>
            <value>
                <fullName>60 days return policy</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Shipping_Information__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Information__c</fullName>
    <label>Shipping Information</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>Ships in 1-2 business days</fullName>
            </value>
            <value>
                <fullName>Ships in 2 weeks</fullName>
            </value>
            <value>
                <fullName>Ships in 1 month</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Sku__c.field-meta.xml
<CustomField>
    <fullName>Sku__c</fullName>
    <externalId>true</externalId>
    <label>SKU</label>
    <length>12</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product__c/fields/Tags__c.field-meta.xml
<CustomField>
    <fullName>Tags__c</fullName>
    <label>Tags</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>beauty</fullName>
            </value>
            <value>
                <fullName>mascara</fullName>
            </value>
            <value>
                <fullName>eyeshadow</fullName>
            </value>
            <value>
                <fullName>face powder</fullName>
            </value>
            <value>
                <fullName>nail polish</fullName>
            </value>
            <value>
                <fullName>fragrances</fullName>
            </value>
            <value>
                <fullName>perfumes</fullName>
            </value>
            <value>
                <fullName>furniture</fullName>
            </value>
            <value>
                <fullName>beds</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Warranty_Information__c.field-meta.xml
<CustomField>
    <fullName>Warranty_Information__c</fullName>
    <label>Warranty Information</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>1 month warranty</fullName>
            </value>
            <value>
                <fullName>2 month warranty</fullName>
            </value>
            <value>
                <fullName>3 month warranty</fullName>
            </value>
            <value>
                <fullName>4 month warranty</fullName>
            </value>
            <value>
                <fullName>5 month warranty</fullName>
            </value>
            <value>
                <fullName>6 month warranty</fullName>
            </value>
            <value>
                <fullName>1 year warranty</fullName>
            </value>
            <value>
                <fullName>2 year warranty</fullName>
            </value>
            <value>
                <fullName>3 year warranty</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Weight__c.field-meta.xml
<CustomField>
    <fullName>Weight__c</fullName>
    <label>Weight</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Review__c/Review__c.object-meta.xml
<CustomObject>
    <label>Review</label>
    <nameField>
        <label>Review Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reviews</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Review__c/fields/Date_time__c.field-meta.xml
<CustomField>
    <fullName>Date_time__c</fullName>
    <label>Date / time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Review__c/fields/Product_Sku__c.field-meta.xml
<CustomField>
    <fullName>Product_Sku__c</fullName>
    <label>Product Sku</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Review__c/fields/Rating__c.field-meta.xml
<CustomField>
    <fullName>Rating__c</fullName>
    <label>Rating</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/DummyProductMapping.cls
public with sharing class DummyProductMapping {
    
    public static String changeReservedWords(String responseBody) {
        responseBody = responseBody.replace('"limit":', '"limit_x":');
        responseBody = responseBody.replace('"date":', '"date_x":');
        return responseBody;
    }

    public static Product__c mapProductFields(JsonParserProduct.Product product) {
        Product__c newProduct = new Product__c();
        newProduct.Availability_Status__c       = product.availabilityStatus;
        newProduct.Warranty_Information__c      = product.warrantyInformation;
        newProduct.Shipping_Information__c      = product.shippingInformation;
        newProduct.Return_Policy__c             = product.returnPolicy;
        newProduct.Minimum_Order_Quantity__c    = product.minimumOrderQuantity;
        newProduct.Weight__c                    = product.weight;
        newProduct.Stock__c                     = product.stock;
        newProduct.Rating__c                    = product.rating;
        newProduct.Discount_Percentage__c       = product.discountPercentage;
        newProduct.Brand__c                     = String.isEmpty(product.brand) ? 'None' : product.brand;
        newProduct.Price__c                     = product.price;
        newProduct.Sku__c                       = product.sku;
        newProduct.Category__c                  = product.category;
        newProduct.Meta_Created_at__c           = parseDateTime(product.meta.createdAt);
        newProduct.Meta_Barcode__c              = product.meta.barcode;
        newProduct.Meta_Qr_Code__c              = product.meta.qrCode;
        newProduct.Meta_Updated_at__c           = parseDateTime(product.meta.updatedAt);
        newProduct.Description__c               = product.description;
        newProduct.Name                         = product.title;
        newProduct.Thumbnail__c                 = product.thumbnail;
        newProduct.Dummy_ID__c                  = product.id;
        newProduct.Dimensions_width__c          = product.dimensions != null ? product.dimensions.width : null;
        newProduct.Dimensions_height__c         = product.dimensions != null ? product.dimensions.height : null;
        newProduct.Dimensions_depth__c          = product.dimensions != null ? product.dimensions.depth : null;
        newProduct.Tags__c                      = product.tags != null ? String.join(new List<String>(product.tags), ';') : null;
        
        fillImgUrls(product.images, newProduct);
        return newProduct;
    }

    public static List<Review__c> mapReviews(List<JsonParserProduct.Review> reviews, String productSku) {
        List<Review__c> reviewList = new List<Review__c>();
        for (JsonParserProduct.Review review : reviews) {
            Review__c newReview = new Review__c();
            newReview.Rating__c = review.rating;
            newReview.Name = review.reviewerName;
            newReview.Date_time__c = parseDateTime(review.date_x);
            newReview.Email__c = review.reviewerEmail;
            newReview.Comment__c = review.comment;
            newReview.Product_Sku__c = productSku;

            reviewList.add(newReview);
        }
        return reviewList;
    }

    public static DateTime parseDateTime(String dateTimeString) {
        try {
            return (DateTime) JSON.deserialize('"' + dateTimeString + '"', DateTime.class);
        } catch (Exception ex) {
            return null;
        }
    }

    public static void fillImgUrls(List<String> listImgs, Product__c newProduct) {
        Integer sizeListImg = listImgs.size();
        if (sizeListImg >= 1) newProduct.Image_1__c = listImgs.get(0);
        if (sizeListImg >= 2) newProduct.Image_2__c = listImgs.get(1);
        if (sizeListImg >= 3) newProduct.Image_3__c = listImgs.get(2);
        if (sizeListImg >= 4) newProduct.Image_4__c = listImgs.get(3);
        if (sizeListImg >= 5) newProduct.Image_5__c = listImgs.get(4);
        if (sizeListImg >= 6) newProduct.Image_6__c = listImgs.get(5);
    }
    
}